[project]
name = "geoapify-car-park"
version = "0.1.0"
description = "This agent returns the car parking spaces near specific coordinates"
authors = [
  { name = "Kshipra Dhame", email = "kshipra.dhame@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.25.4",
  "uagents-core>=0.4.9",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
