[project]
name = "github-organisation-agent"
version = "0.1.0"
description = "This agent returns github repository information of a given company name"
authors = [
  { name = "Kshipra Dhame", email = "kshipra.dhame@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.18.1",
  "requests>=2.32.3",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
