[project]
name = "post-extractor-agent"
version = "0.1.0"
description = "This agent retrieves the latest requested posts from Reddit"
authors = [
  { name = "Alejandro", email = "alejandro.madrigal@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.25.4",
  "uagents-core>=0.4.9",
  "requests>=2.32.3",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
