[project]
name = "claude-agent"
version = "0.1.0"
description = "This agent is a wrapper around the Claude.ai interface"
authors = [
  { name = "Florian Wilde", email = "florian.wilde@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.22.4",
  "uagents-core>=0.3.1",
  "requests>=2.32.3",
]

[tool.poetry]
packages = [{ include = "claude" }]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
