[project]
name = "gemini-agent"
version = "0.1.0"
description = "This agent is a simple wrapper around Google's Gemini Large Language Model"
authors = [
  { name = "Florian Wilde", email = "florian.wilde@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "uagents>=0.25.4",
  "uagents-core>=0.4.9",
  "google-genai>=1.4.0",
]

[tool.poetry]
packages = [{ include = "gemini" }]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
