name: ☝️Request
description: Suggest an idea for an uAgent, solution or application.
labels: ["enhancement", "unconfirmed"]
assignees:
  - jrriehl
  - Archento
  - qati
  - devjsc
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new idea! Please complete the following so we have everything to get started.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting a feature request.
      options:
        - label: I checked the [existing issues](https://github.com/fetchai/uAgent-Examples/issues) to make sure this feature has not already been requested
          required: true
  - type: textarea
    id: item
    attributes:
      label: Item
      description: |
        Provide a description of the item (uAgent, solution, application) you would like to see implemented.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional Information (Optional)
      description: |
        Add any other context, screenshots, or information that could be helpful for understanding your request.
    validations:
      required: false
