[project]
name = "blog-creator-agent"
version = "0.1.0"
description = "This agent combines a topic extraction agent with a blog generator, transforming Reddit posts into a blog based on a chosen topic."
authors = [
  { name = "Alejandro", email = "alejandro.madrigal@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.22.0",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"