[project]
name = "finbert-sentiment-agent"
version = "0.1.0"
description = "This agent helps you to get finbert sentiment of a given financial text."
authors = [
  { name = "abhifetch", email = "abhi.gangani@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.22.0",
  "requests>=2.32.3",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
