[project]
name = "google-maps-places-agent"
version = "0.1.0"
description = "This agent exposes the Google places API via a simple POI protocol"
authors = [
  { name = "Dacksus", email = "david.noack@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.22.0",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
