[project]
name = "open-charge-map-agent"
version = "0.1.0"
description = "This agent will return a list of EV Chargers wrapped as a Point of Interest"
authors = [
  { name = "Florian Wilde", email = "florian.wilde@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.22.0",
  "requests>=2.32.3",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
