[project]
name = "finance-qa-agent"
version = "0.1.0"
description = "This agent provides answers to questions related to finance and economics"
authors = [
  { name = "Beniamino Daniele", email = "beniamino.daniele@fetch.ai" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "uagents>=0.25.4",
  "uagents-core>=0.4.9",
  "openai>=1.16.1",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
