[tool.poetry]
name = "claude-agent"
version = "0.1.0"
description = ""
authors = ["Florian Wilde <florian.wilde@fetch.ai>"]
readme = "README.md"
packages = [{ include = "claude" }]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
uagents = "^0.15.2"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
